version: "3.6"

services:
  client:
    image: node:11-alpine
    entrypoint: ash
    command: " -c 'npm start' "
    ports:
      - "${FRONT_END_PORT}:${FRONT_END_PORT}"
    volumes:
      - ./client:/client
    working_dir: /client
    depends_on:
      - database

  server:
    image: node:11-alpine
    entrypoint: ash
    command: " -c 'npm run server:dev' "
    ports:
      - 3000:3000
    volumes: 
      - ./server:/server
    working_dir: /server

  database:
    image: postgres:11.5-alpine
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 'npc_gen'
      POSTGRES_USER: 'npc_gen'
      POSTGRES_DB: "npc_gen"
      PGDATA: ./server/db
